torantie's solution for Project
mimuc/gp-ws2021 pull request #25
Opened 2021-02-14 22:35 UTC by torantie

Unfortunately could not find the error in the Mean value weights calculation.

2021-03-01 08:47 UTC, changkun requested changes
Code haven't review yet, let's first get the licensing of your code right :)

2021-03-01 08:47 UTC, changkun commented on projects/torantie/package.json
> +  "name": "gp-3-smooth",
Remember to change this to your project name

2021-03-01 08:47 UTC, changkun commented on projects/torantie/package.json
> +  "author": "Changkun Ou",
Change the author to your name or your github username

2021-03-01 08:47 UTC, changkun commented on projects/torantie/package.json
> +  "license": "GPL-3.0",
Maybe more information about GPLv3 that might be good to know for your future open source work:

```
GNU GPLv3:
1. Anyone can copy, modify and distribute this software.
2. You have to include the license and copyright notice with each and every distribution.
3. You can use this software privately.
4. You can use this software for commercial purposes.
5. If you dare build your business solely from this code, you risk open-sourcing the whole code base.
6. If you modify it, you have to indicate changes made to the code.
7. Any modifications of this code base MUST be distributed with the same license, GPLv3.
8. This software is provided without warranty.
9. The software author or license can not be held liable for any damages inflicted by the software.
```

Full: https://github.com/mimuc/gp-ws2021/blob/master/LICENSE

2021-03-01 08:47 UTC, changkun commented on projects/torantie/src/halfedge.js
> +// API Usage about @penrose/linear-algebra:
```
/**
 * Copyright © 2021 YOUR NAME <YOUR DOMAIN>. All rights reserved.
 * Portions Copyright © 2020-2021 Changkun Ou (contact@changkun.de)
 * 
 * Use of this source code is governed by a GNU GLPv3 license that can be
 * found in the LICENSE file.
 */

```

Add the above comments to the top of every source code file that you care about your originality.
Change the following information that fits your case:

1. Add your name and your domain (if possible)
2. Remove the `Portions ...` line if a file is not derived from my solution and completely newly added

2021-03-01 11:02 UTC, changkun requested changes

2021-03-01 11:02 UTC, changkun commented on projects/torantie/src/halfedge.js
> +/**
Should be on top of the file starting from line 1 :)

2021-03-06 17:22 UTC, changkun approved these changes
- Nice teamwork on the quad support.
- Nice huge variety of comparison on different smoothing methods.

Regarding the mean value weights does not work, I just spend some time on reading an existing UnrealEngine 4.6's implementation: 

https://github.com/EpicGames/UnrealEngine/blob/5cf13708ed609c390e1cb2d27e2dd48c11423acd/Engine/Plugins/Experimental/GeometryProcessing/Source/DynamicMesh/Private/Solvers/PrecomputedMeshWeightData.cpp#L169-L208

https://github.com/EpicGames/UnrealEngine/blob/2bf1a5b83a7076a0fd275887b373f8ec9e99d431/Engine/Plugins/Experimental/GeometryProcessing/Source/DynamicMesh/Public/Solvers/PrecomputedMeshWeightData.h#L131-L142

https://github.com/EpicGames/UnrealEngine/blob/2bf1a5b83a7076a0fd275887b373f8ec9e99d431/Engine/Plugins/Experimental/GeometryProcessing/Source/DynamicMesh/Public/Solvers/LaplacianMatrixAssembly.h#L390-L455

Especially the thrid link. If you are interested in how they did it, it might be useful for you to read :)

From what I read at the moment, they did a lot precaution for numerical calculation, and there is an interesting prevention on boundary edges:

https://github.com/EpicGames/UnrealEngine/blob/2bf1a5b83a7076a0fd275887b373f8ec9e99d431/Engine/Plugins/Experimental/GeometryProcessing/Source/DynamicMesh/Public/Solvers/LaplacianMatrixAssembly.h#L437

Thus, I think overall your implementation is almost right, the weighted sum for the (ij, i != j) interior laplacian matrix, and the sum of all weights for the (ij, i==j) boundary laplacian.

By the way, I did a small typo change to your implementation:

```diff
-      weightTriplet.addEntry(sum/*/count*/, i, i)
+      weightTriplet.addEntry(-sum/*/count*/, i, i)
```

and I got a very interesting and promising result:

![image](https://user-images.githubusercontent.com/5498964/110215135-82dc1900-7ea8-11eb-9873-56d3c62f64eb.png)

![image](https://user-images.githubusercontent.com/5498964/110215190-bb7bf280-7ea8-11eb-8a9a-01d650f8a8db.png)

The overall shape is very close (especially the bunny in the second figure), but clearly there should (might) be some numerical issue that exists that prevents you from getting a good result.

2021-03-06 17:24 UTC, merged

2021-03-08 15:06 UTC, torantie commented
interesting change negating the sum in the weight triplet. The shape does seem more promising. What i kind of find weird is that with this change both the sum and the individual values (in the code called "w") are now negated.
```
vert.forEachHalfEdge(h => {
        let w = 0

        count++
        switch (weightType) {
          case 'uniform':
            w = 1
            break;
          case 'cotan':
            w = (h.cotan() + h.twin.cotan())/2
            break;
          case 'mean value':
            w = h.meanValueWeight()
            break;
        }


        sum += w
        weightTriplet.addEntry(-w, i, h.twin.vertex.idx)
      })
      weightTriplet.addEntry(sum/*/count*/, i, i)
```
Based on the Laplacian definition in the lecture only the sum should be negated.
![image](https://user-images.githubusercontent.com/14915789/110337258-0111fa00-8026-11eb-8d19-cbce7b6e42a9.png)
But since I (and the solution of exercise 5) used formula with Mass Matrix + Laplacian matrix, we negated the w not the sum.
`
let f = M.plus(W.timesReal(timeStep).timesReal(lambda))
`
If we use Mass Matrix minus Weight Martix we can negate the sum and leave the "w" without a minus.
At least these two versions where the only ones where uniform and cotan weights still worked. With the version where the w and sum are negated we get something like this for cotan for example, which seems kind of similar to the result of mean value weights:
![image](https://user-images.githubusercontent.com/14915789/110338385-39fe9e80-8027-11eb-818f-9e654f3abc8a.png)
Is also tested the version (both w and sum negated) with lower values of lambda, but it seems that the deformation is also very high when the weight matrix is scaled down. So I am not so sure if the change actually provides a better result.
![image](https://user-images.githubusercontent.com/14915789/110338207-0ae82d00-8027-11eb-822b-bc119afcacea.png)

Thank you for the unreal engine links. Unfortunately i am not able to access them (404 Page not found). Did the repository change or do i need something else to view their github?

2021-03-09 12:28 UTC, changkun commented
> Did the repository change or do i need something else to view their github?

The repo is private, you need to signup for the unreal engine to get access to the repository (free), there are some instructions:

https://www.unrealengine.com/en-US/ue4-on-github